### ISSUE TITLE
개별 모드에 PR은 자동으로 되는 거임?

### ISSUE THREAD

**Issue by AsseyGithub** [Soochaehwa/Korean-Resource-Pack#2]
ㅇㅇ

**Comment by Soochaehwa** [comment]
[번역 리소스팩](https://github.com/Soochaehwa/Korean-Resource-Pack/releases)만 자동으로 릴리즈하고
모드 저장소에 PR은 안함

모드에 번역 추가하고싶으면
번역 파일 받아서 개인적으로 PR하면 될 듯
