### ISSUE TITLE
일괄 번역은 어케하는거임?

### ISSUE THREAD

**Issue by qkrehf2** [Soochaehwa/Korean-Resource-Pack#3]
도구 > 검색 및 바꾸기로 하는거 같은데 왜 안되지

**Comment by Soochaehwa** [comment]
![711](https://user-images.githubusercontent.com/43947445/172005702-98e65bad-d1a0-4b76-8ce6-770ec4b153d5.png)
저리 안뜸?
권한을 따로 줘야하나???

**Comment by qkrehf2** [comment]
![image](https://user-images.githubusercontent.com/64183602/172036632-1ff96ff2-22c4-48ca-9ed0-4a023b71081d.png)
이렇게만 뜨고 뭐 문자열 입력해도 안나오던데

**Comment by Soochaehwa** [comment]
저 화면에서 검색문자열에 찾을 단어, 교체 문자열에 바꿀 단어 적고 교체누르면 내가 올린 화면 뜸

**Comment by qkrehf2** [comment]
ㅇㅎ 근데 되는것도 있고 안되는 것도 있는데 뭔차이지
https://weblate.shwa.space/projects/forge-1-18/additionalbanners/ko_kr/
여기서 색 이름 다 바꿀려고하는데 검색과 재배치가 완료되었고, 문자열이 업데이트 되지 않았습니다. 이것만 뜨네

**Comment by qkrehf2** [comment]
아 이미 번역되어있는걸 바꾸는 거구나 이런

**Comment by qkrehf2** [comment]
번역안된 동일한 단어들 한번에 번역하는방법없나
일일이 파일받고 업로드하긴 귀찮은디

**Comment by Soochaehwa** [comment]
![733](https://user-images.githubusercontent.com/43947445/172612020-a596dd7b-61a0-4600-993d-56eee1c96e22.png)
애드온중에 이거 있는데 이거쓰고 replace하면 될려나?

**Comment by qkrehf2** [comment]
ㄱㄱㄱㄱ

**Comment by Soochaehwa** [comment]
모드명 알려주면 저거 적용해놓음
