### ISSUE TITLE
번역 스타일 추가

### ISSUE THREAD

**Issue by qkrehf2** [Soochaehwa/Korean-Resource-Pack#7]
크리에이티브 아이템 탭 이름은 번역하지 않기
itemGroup.creativeTab으로 되어있나 그럴거임

예외 : 모드 뒤에 일반 명사 붙으면 그건 번역함
Create > Create
Create Palette > Create 팔레트
(모드 이름) Building Blocks > (모드 이름) 건축 블록

**Comment by Soochaehwa** [comment]
탭 이름에 있는 모드명만 번역 안하는거임?
탭말고 다른곳에 나오는 모드명은 어떻게 함?

**Comment by qkrehf2** [comment]
모드명은 고유명사니까 번역안하징

**Comment by Soochaehwa** [comment]
ㅇㅋ 그러면 

## 기본 원칙
1. 한국어 맞춤법을 지킵니다.
2. 번역 투를 지양하며 자연스럽게 번역합니다.
3. 본래의 의미를 전달할 수 있도록 오역하지 않아야 합니다.
4. 용어집에 있는 단어의 경우 가능한 용어집을 따릅니다.
5. 번역 키를 확인하여 주석이거나 게임에서 쓰이지 않는 문자열은 번역하지 않습니다.
6. 모드 이름은 번역하지 않습니다.

모드 이름만 번역안하면 아이템 탭도 니가 예시로든거 해결되니까 이렇게하면 괜찮을거같음?

**Comment by Fellal1** [comment]
bigger reactor 같은경우에는 번역함? 아님 그대로 납두냐?

**Comment by qkrehf2** [comment]
ㅇㅇ 냅둬 
모드 이름도 번역하면
'창조'
"몰입형 공학'
'열역학 팽창'
'기계장치'
'응용 에너지학'  이렇게 되느니 원문 그대로 두는게 좋을거 같음

**Comment by Fellal1** [comment]
ㅇㅋ

**Comment by Fellal1** [comment]
하나 더 궁금한게있는데 ctrl 이나 shift 같은 키를 번역하는건 컨트롤 쉬프트 이런식 말고 그냥 영문 그대로 번역함?

**Comment by Soochaehwa** [comment]
@Fellal1 ㅇㅇ 키보드 키는 영문 그대로 쓰면 됨

@qkrehf2 내가 처음 표현을 잘못했네 그렇게 모드명을 그렇게 직접적으로 번역하자는게 아니라 대부분의 모드들이 음차 해놓은거 어떻게하냐고 물어본거였음

**Comment by qkrehf2** [comment]
늦게봤노 
나는 원문으로 가는게 더 좋을거 같음
