### ISSUE TITLE
용어집 삭제 기능

### ISSUE THREAD

**Issue by adfa0107** [Soochaehwa/Korean-Resource-Pack#9]
https://weblate.shwa.space/translate/forge-1-18/glossary/ko_kr/?checksum=6363b3b4fb2dda25
https://weblate.shwa.space/translate/forge-1-18/glossary/ko_kr/?checksum=44c33d75ded3e907

프리즈머린이랑 퍼퍼 등록하려고 했는데 실수로 Prismarine Door, Purpur Door로 등록해서 삭제해야할 것 같은데 삭제 기능이 안보이네 직접 삭제하거나 삭제 기능 추가해줘야 할 것 같음

**Comment by Soochaehwa** [comment]
지웠음

![780](https://user-images.githubusercontent.com/43947445/175540002-451f11f7-a07f-4052-a527-191a28807302.png)
그리고 다른 문자열 들어가서 
사진처럼 도구 - Delete string 뜨는지 확인좀

**Comment by adfa0107** [comment]
![image](https://user-images.githubusercontent.com/107128479/175546614-950bd433-9657-48ab-8c90-fd0fea6fa051.png)
잘 뜸

**Comment by Soochaehwa** [comment]
원래 번역에는 저런거 없음
용어집에만 뜨는게 정상
